name = "KIRO2022"
authors = ["Adle Ben Salem | adle.ben-salem@eleves.enpc.fr"]
version = "0.1.0"

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
